# Generated by Django 4.0.4 on 2022-04-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.CharField(error_messages={'unique': 'A bank account with the account number already exists.'}, max_length=50, unique=True),
        ),
    ]
