# Generated by Django 4.0.4 on 2022-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_aadhaar_options_rename_line_2_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=250),
        ),
    ]
