# Generated by Django 4.0.4 on 2022-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative '), ('O+', 'O positive'), ('O-', 'O negative'), ('AB+', 'AB positive'), ('AB-', 'AB negative')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
    ]
