# Generated by Django 4.0.4 on 2022-04-29 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_blood_group_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(default='908ef7eb-a07f-4063-829e-04a9941fd78f', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='user',
            field=models.ForeignKey(default='908ef7eb-a07f-4063-829e-04a9941fd78f', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
