# Generated by Django 4.0.4 on 2022-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailaddress_user_phone_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
