# Generated by Django 4.0.4 on 2022-04-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pastjobexperience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='PastJobExperience',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
